-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 20:06:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Balabox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Balabox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Balabox` DEFAULT CHARACTER SET utf8 ;
USE `Balabox` ;

-- -----------------------------------------------------
-- Table `Balabox`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `Tipo_usuario` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(80) NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `ApellidoP` VARCHAR(40) NOT NULL,
  `ApellidoM` VARCHAR(40) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(8) NOT NULL,
  `Fecha_registro` DATE NOT NULL,
  `Imagen` MEDIUMBLOB NULL,
  `TipoUsuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `TipoUsuario_idUsuario`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) ,
  UNIQUE INDEX `Fecha_registro_UNIQUE` (`Fecha_registro` ASC) ,
  INDEX `fk_Usuario_TipoUsuario1_idx` (`TipoUsuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario_idUsuario`)
    REFERENCES `Balabox`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `NombreEmpresa` VARCHAR(50) NOT NULL,
  `GiroEmpresa` VARCHAR(45) NOT NULL,
  `ServiciosDeInteres` VARCHAR(15) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `Usuario_idUsuario`),
  INDEX `fk_Empresa_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  UNIQUE INDEX `NombreEmpresa_UNIQUE` (`NombreEmpresa` ASC) ,
  CONSTRAINT `fk_Empresa_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Balabox`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Cotizacion` (
  `idCotizacion` INT NOT NULL AUTO_INCREMENT,
  `Servicio` VARCHAR(40) NOT NULL,
  `Explicacion` TEXT(1) NOT NULL,
  `Nota` MEDIUMTEXT NOT NULL,
  `Archivos` MEDIUMBLOB NULL,
  `TituloDelProyecto` VARCHAR(45) NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idCotizacion`, `Empresa_idEmpresa`),
  INDEX `fk_Cotizacion_Empresa1_idx` (`Empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_Cotizacion_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Balabox`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `NombreProyecto` VARCHAR(65) NOT NULL,
  `FechaEnterga` DATE NOT NULL,
  `Garantia` INT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `Empresa_idEmpresa`),
  INDEX `fk_Proyecto_Empresa1_idx` (`Empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_Proyecto_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Balabox`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`ComentarioSoporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`ComentarioSoporte` (
  `idComentarioSoporte` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Comentario` MEDIUMTEXT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Proyecto_Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idComentarioSoporte`, `Usuario_idUsuario`, `Proyecto_idProyecto`, `Proyecto_Empresa_idEmpresa`),
  INDEX `fk_ComentarioSoporte_Usuario_idx` (`Usuario_idUsuario` ASC) ,
  INDEX `fk_ComentarioSoporte_Proyecto1_idx` (`Proyecto_idProyecto` ASC, `Proyecto_Empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_ComentarioSoporte_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Balabox`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComentarioSoporte_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto` , `Proyecto_Empresa_idEmpresa`)
    REFERENCES `Balabox`.`Proyecto` (`idProyecto` , `Empresa_idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`ComentarioCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`ComentarioCliente` (
  `idComentarioCliente` INT NOT NULL AUTO_INCREMENT,
  `Comentario` MEDIUMTEXT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Imagen` MEDIUMBLOB NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Proyecto_Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idComentarioCliente`, `Proyecto_idProyecto`, `Proyecto_Empresa_idEmpresa`),
  INDEX `fk_ComentarioCliente_Proyecto1_idx` (`Proyecto_idProyecto` ASC, `Proyecto_Empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_ComentarioCliente_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto` , `Proyecto_Empresa_idEmpresa`)
    REFERENCES `Balabox`.`Proyecto` (`idProyecto` , `Empresa_idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`TicketSoporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`TicketSoporte` (
  `Ticket` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(7) NOT NULL,
  `Fecha` DATE NOT NULL,
  `ComentarioSoporte_idComentarioCliente` INT NOT NULL,
  `ComentarioCliente_idComentarioSoporte` INT NOT NULL,
  PRIMARY KEY (`Ticket`, `ComentarioSoporte_idComentarioCliente`, `ComentarioCliente_idComentarioSoporte`),
  INDEX `fk_TicketSoporte_ComentarioSoporte1_idx` (`ComentarioSoporte_idComentarioCliente` ASC) ,
  INDEX `fk_TicketSoporte_ComentarioCliente1_idx` (`ComentarioCliente_idComentarioSoporte` ASC) ,
  CONSTRAINT `fk_TicketSoporte_ComentarioSoporte1`
    FOREIGN KEY (`ComentarioSoporte_idComentarioCliente`)
    REFERENCES `Balabox`.`ComentarioSoporte` (`idComentarioSoporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TicketSoporte_ComentarioCliente1`
    FOREIGN KEY (`ComentarioCliente_idComentarioSoporte`)
    REFERENCES `Balabox`.`ComentarioCliente` (`idComentarioCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Ofertas` (
  `idOfertas` INT NOT NULL AUTO_INCREMENT,
  `NombreOferta` VARCHAR(66) NOT NULL,
  `FechaExpiracion` DATE NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `imagen` MEDIUMBLOB NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idOfertas`, `Usuario_idUsuario`),
  INDEX `fk_Ofertas_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Ofertas_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Balabox`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Satisfaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Satisfaccion` (
  `idSatisfaccion` INT NOT NULL AUTO_INCREMENT,
  `Pregunta1` INT NULL,
  `Pregunta2` INT NULL,
  `Pregunta3` INT NULL,
  `TicketSoporte_Ticket` INT NOT NULL,
  PRIMARY KEY (`idSatisfaccion`),
  INDEX `fk_Satisfaccion_TicketSoporte1_idx` (`TicketSoporte_Ticket` ASC) ,
  CONSTRAINT `fk_Satisfaccion_TicketSoporte1`
    FOREIGN KEY (`TicketSoporte_Ticket`)
    REFERENCES `Balabox`.`TicketSoporte` (`Ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Balabox`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Balabox`.`Ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(25) NOT NULL,
  `Pais` VARCHAR(25) NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idUbicacion`),
  INDEX `fk_Ubicacion_Empresa1_idx` (`Empresa_idEmpresa` ASC) ,
  CONSTRAINT `fk_Ubicacion_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Balabox`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
